<?php

namespace Jazzyweb\AulasMentor\NotasFrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaRepository extends EntityRepository
{
    public function findByUsuarioOrderedByNombre($username){
        $query = $this->getEntityManager()->createQuery(
                        "SELECT t FROM JAMNotasFrontendBundle:Tema t
                      JOIN  t.propietario p where p.id = :username ORDER BY t.nombre ASC")
                ->setParameters(array('username' => $username));

        $temas = $query->getResult();
        
        return $temas;
    }
}
